# Generated by Django 4.0.3 on 2024-03-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwin', '0004_car_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeTimeScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
            ],
        ),
    ]
