# Generated by Django 4.0.3 on 2024-03-29 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwin', '0005_chargetimescores'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargetimescores',
            name='scores',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.int_list_validator]),
        ),
    ]
