# Generated by Django 4.0.3 on 2024-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwin', '0006_chargetimescores_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
