# Generated by Django 4.0.3 on 2024-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwin', '0007_car_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_state',
            field=models.CharField(default='plugged_in', max_length=100),
            preserve_default=False,
        ),
    ]
